#!/usr/bin/perl -w

use OFCS::Client;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "OFCS-Client",
   ReceiveHandler => \&Receive);
$UNIVERSAL::ofcsclient = OFCS::Client->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::ofcsclient->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::ofcsclient->Execute();
